name: mkmetrics
version: 0.1.0
github: "changsun20/mkmetrics"
author: "changsun20"
license: BSD-3-Clause

extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >=4.7 && <5
  - text >=2.1.1
  - optparse-applicative >=0.18

flags:
  static:
    description: Build static executable
    manual: true
    default: false

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - CLI
    - Output
    - Stats.Basic
    - Stats.Core
    - Stats.Markdown
    - Stats.Types
  other-modules: []

executable:
  main: Main.hs
  source-dirs: src
  dependencies:
    - mkmetrics
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  when:
    - condition: flag(static)
      ghc-options:
        - -static
        - -optl-static
        - -optl-pthread
        - -optc-Os

tests:
  mkmetrics-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mkmetrics
      - hspec >= 2.7.1
      - QuickCheck
      - hspec-discover
      - text
      - directory
      - filepath
      - silently

