name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        resolver: [lts-23.27]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Haskell Stack
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "latest"
          enable-stack: true
          stack-version: "latest"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ matrix.resolver }}-${{ hashFiles('**/*.cabal', 'stack.yaml', 'package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-${{ matrix.resolver }}-
            ${{ runner.os }}-stack-

      - name: Install dependencies
        run: stack build --resolver ${{ matrix.resolver }} --dependencies-only

      - name: Build project
        run: stack build --resolver ${{ matrix.resolver }}

      - name: Run tests
        run: stack test --resolver ${{ matrix.resolver }}

